import jsPDF from "jspdf";

type Labels = {
  header: string;
  ref: string;
  date: string;
  time: string;
  agent: string;
  location: string;
  type: string;
  infoGeneral: string;
  context: string;
  facts: string;
  declarations: string;
  observations: string;
  conclusion: string;
  signature: string;
  signedBy: string;
  pageOf: (i: number, n: number) => string;
  generatedBy: string;
  typeRapport: string;
  typePv: string;
};

const FR: Labels = {
  header: "AURUM SYSTEM",
  ref: "Référence",
  date: "Date",
  time: "Heure",
  agent: "Agent",
  location: "Lieu",
  type: "Type",
  infoGeneral: "INFORMATIONS GÉNÉRALES",
  context: "CONTEXTE",
  facts: "FAITS CONSTATÉS",
  declarations: "DÉCLARATIONS RECUEILLIES",
  observations: "OBSERVATIONS",
  conclusion: "CONCLUSION",
  signature: "SIGNATURE",
  signedBy: "Signé par",
  pageOf: (i, n) => `Page ${i} / ${n}`,
  generatedBy: "Généré par AURUM SYSTEM · Cameroun",
  typeRapport: "RAPPORT",
  typePv: "PROCÈS-VERBAL",
};

const EN: Labels = {
  header: "AURUM SYSTEM",
  ref: "Reference",
  date: "Date",
  time: "Time",
  agent: "Agent",
  location: "Location",
  type: "Type",
  infoGeneral: "GENERAL INFORMATION",
  context: "CONTEXT",
  facts: "FACTS OBSERVED",
  declarations: "STATEMENTS COLLECTED",
  observations: "OBSERVATIONS",
  conclusion: "CONCLUSION",
  signature: "SIGNATURE",
  signedBy: "Signed by",
  pageOf: (i, n) => `Page ${i} / ${n}`,
  generatedBy: "Generated by AURUM SYSTEM · Cameroon",
  typeRapport: "REPORT",
  typePv: "MINUTES",
};

export type DocForPdf = {
  type: "rapport" | "pv" | "recensement" | "enquete";
  title: string;
  introduction: string;
  faits: string;
  declarations: string;
  observations?: string;
  conclusion: string;
  created_at?: string;
  doc_date?: string | null;
  doc_time?: string | null;
  agent_name?: string;
  location?: string;
  reference?: string;
  signature_name?: string;
  lang?: string;
  /** Data URLs (base64) for photos. Must be pre-resolved before calling export. */
  photo_data_urls?: string[];
};

export function exportDocumentPdf(doc: DocForPdf) {
  const L = (doc.lang === "en" ? EN : FR);
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 48;
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const contentWidth = pageWidth - margin * 2;
  let y = 0;

  const ensureSpace = (h: number) => {
    if (y + h > pageHeight - 60) {
      pdf.addPage();
      drawHeader();
    }
  };

  const drawHeader = () => {
    // Gold band
    pdf.setFillColor(20, 20, 20);
    pdf.rect(0, 0, pageWidth, 70, "F");
    // Gold stripe
    pdf.setFillColor(201, 168, 76);
    pdf.rect(0, 70, pageWidth, 3, "F");

    // Mini logo block
    pdf.setFillColor(201, 168, 76);
    pdf.roundedRect(margin, 18, 36, 36, 6, 6, "F");
    pdf.setTextColor(20, 20, 20);
    pdf.setFont("times", "bold");
    pdf.setFontSize(22);
    pdf.text("A", margin + 12, 44);

    // Title
    pdf.setTextColor(232, 196, 100);
    pdf.setFont("times", "bold");
    pdf.setFontSize(18);
    pdf.text(L.header, margin + 50, 35);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(200, 200, 200);
    pdf.text(doc.type === "rapport" ? L.typeRapport : L.typePv, margin + 50, 52);

    // Right: reference
    if (doc.reference) {
      pdf.setFontSize(9);
      pdf.setTextColor(220, 220, 220);
      const ref = `${L.ref}: ${doc.reference}`;
      pdf.text(ref, pageWidth - margin, 38, { align: "right" });
    }
    y = 92;
  };

  drawHeader();

  // Title
  pdf.setTextColor(20, 20, 20);
  pdf.setFont("times", "bold");
  pdf.setFontSize(20);
  const titleLines = pdf.splitTextToSize(doc.title || (doc.type === "rapport" ? L.typeRapport : L.typePv), contentWidth);
  pdf.text(titleLines, margin, y);
  y += titleLines.length * 22 + 6;

  pdf.setDrawColor(201, 168, 76);
  pdf.setLineWidth(1.2);
  pdf.line(margin, y, margin + 70, y);
  y += 22;

  // INFOS GÉNÉRALES box
  const dateStr = doc.doc_date
    ? new Date(doc.doc_date).toLocaleDateString(doc.lang === "en" ? "en-GB" : "fr-FR", { day: "2-digit", month: "long", year: "numeric" })
    : doc.created_at
      ? new Date(doc.created_at).toLocaleDateString(doc.lang === "en" ? "en-GB" : "fr-FR", { day: "2-digit", month: "long", year: "numeric" })
      : "—";
  const timeStr = doc.doc_time
    ? doc.doc_time.slice(0, 5)
    : doc.created_at
      ? new Date(doc.created_at).toLocaleTimeString(doc.lang === "en" ? "en-GB" : "fr-FR", { hour: "2-digit", minute: "2-digit" })
      : "—";

  const infos: Array<[string, string]> = [
    [L.date, dateStr],
    [L.time, timeStr],
    [L.agent, doc.agent_name || "—"],
    [L.location, doc.location || "—"],
    [L.type, doc.type === "rapport" ? L.typeRapport : L.typePv],
    [L.ref, doc.reference || "—"],
  ];

  pdf.setFont("times", "bold");
  pdf.setFontSize(11);
  pdf.setTextColor(120, 95, 30);
  pdf.text(L.infoGeneral, margin, y);
  y += 14;

  pdf.setDrawColor(220, 220, 220);
  pdf.setLineWidth(0.5);
  const rowH = 18;
  const colW = contentWidth / 2;
  const boxTop = y;
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.setTextColor(60, 60, 60);
  for (let i = 0; i < infos.length; i++) {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = margin + col * colW;
    const ry = boxTop + row * rowH;
    pdf.setTextColor(140, 140, 140);
    pdf.text(infos[i][0].toUpperCase(), x + 8, ry + 7);
    pdf.setTextColor(20, 20, 20);
    const val = pdf.splitTextToSize(infos[i][1], colW - 100);
    pdf.text(val, x + 100, ry + 7);
  }
  const boxBottom = boxTop + Math.ceil(infos.length / 2) * rowH + 4;
  pdf.setDrawColor(220, 220, 220);
  pdf.rect(margin, boxTop - 8, contentWidth, boxBottom - boxTop + 4);
  y = boxBottom + 20;

  // Sections
  const sections: Array<{ heading: string; body: string }> = [
    { heading: L.context, body: doc.introduction },
    { heading: L.facts, body: doc.faits },
    { heading: L.declarations, body: doc.declarations },
    { heading: L.observations, body: doc.observations || "—" },
    { heading: L.conclusion, body: doc.conclusion },
  ];

  for (const s of sections) {
    ensureSpace(50);
    pdf.setFont("times", "bold");
    pdf.setFontSize(12);
    pdf.setTextColor(120, 95, 30);
    pdf.text(s.heading, margin, y);
    // underline
    pdf.setDrawColor(201, 168, 76);
    pdf.setLineWidth(0.6);
    pdf.line(margin, y + 3, margin + pdf.getTextWidth(s.heading), y + 3);
    y += 16;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10.5);
    pdf.setTextColor(30, 30, 30);
    const lines = pdf.splitTextToSize(s.body || "—", contentWidth);
    for (const line of lines) {
      ensureSpace(15);
      pdf.text(line, margin, y);
      y += 14;
    }
    y += 12;
  }

  // Photos (pre-resolved data URLs only; no async work here) — rendered ONCE
  const photos = doc.photo_data_urls?.filter(Boolean) ?? [];
  if (photos.length > 0) {
    ensureSpace(40);
    pdf.setFont("times", "bold");
    pdf.setFontSize(12);
    pdf.setTextColor(120, 95, 30);
    const heading = "PHOTOS";
    pdf.text(heading, margin, y);
    pdf.setDrawColor(201, 168, 76);
    pdf.setLineWidth(0.6);
    pdf.line(margin, y + 3, margin + pdf.getTextWidth(heading), y + 3);
    y += 14;

    const gap = 8;
    const cols = 2;
    const cellW = (contentWidth - gap * (cols - 1)) / cols;
    const cellH = cellW * 0.75;
    let col = 0;
    for (const dataUrl of photos) {
      if (col === 0) ensureSpace(cellH + gap);
      const x = margin + col * (cellW + gap);
      try {
        const fmt = dataUrl.startsWith("data:image/png") ? "PNG" : "JPEG";
        pdf.addImage(dataUrl, fmt, x, y, cellW, cellH, undefined, "FAST");
      } catch {
        pdf.setDrawColor(220, 220, 220);
        pdf.rect(x, y, cellW, cellH);
      }
      col++;
      if (col >= cols) {
        col = 0;
        y += cellH + gap;
      }
    }
    if (col !== 0) y += cellH + gap;
    y += 8;
  }

  // Signature block
  ensureSpace(110);
  y += 10;
  pdf.setFont("times", "bold");
  pdf.setFontSize(11);
  pdf.setTextColor(120, 95, 30);
  pdf.text(L.signature, margin, y);
  y += 14;
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.setTextColor(60, 60, 60);
  pdf.text(`${L.signedBy} : ${doc.signature_name || doc.agent_name || "—"}`, margin, y);
  y += 10;
  // signature line
  pdf.setDrawColor(150, 150, 150);
  pdf.setLineWidth(0.4);
  pdf.rect(margin, y + 6, 240, 60);
  y += 80;

  // Footer on every page
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setDrawColor(201, 168, 76);
    pdf.setLineWidth(0.5);
    pdf.line(margin, pageHeight - 36, pageWidth - margin, pageHeight - 36);
    pdf.setFontSize(8);
    pdf.setTextColor(130, 130, 130);
    pdf.text(L.generatedBy, margin, pageHeight - 22);
    if (doc.reference) {
      pdf.text(`${L.ref}: ${doc.reference}`, pageWidth / 2, pageHeight - 22, { align: "center" });
    }
    pdf.text(L.pageOf(i, pageCount), pageWidth - margin, pageHeight - 22, { align: "right" });
  }

  const safe = (doc.title || "aurum-document").replace(/[^a-z0-9-_]+/gi, "-").slice(0, 60);
  pdf.save(`${safe || "document"}.pdf`);
}
