/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedSupervisorRouteImport } from './routes/_authenticated.supervisor'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedRecensementsRouteImport } from './routes/_authenticated.recensements'
import { Route as AuthenticatedRecensementRouteImport } from './routes/_authenticated.recensement'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated.new'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedRecordTypeRouteImport } from './routes/_authenticated.record.$type'
import { Route as AuthenticatedDocumentIdRouteImport } from './routes/_authenticated.document.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupervisorRoute = AuthenticatedSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecensementsRoute =
  AuthenticatedRecensementsRouteImport.update({
    id: '/recensements',
    path: '/recensements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecensementRoute =
  AuthenticatedRecensementRouteImport.update({
    id: '/recensement',
    path: '/recensement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecordTypeRoute = AuthenticatedRecordTypeRouteImport.update({
  id: '/record/$type',
  path: '/record/$type',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentIdRoute = AuthenticatedDocumentIdRouteImport.update({
  id: '/document/$id',
  path: '/document/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/new': typeof AuthenticatedNewRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recensement': typeof AuthenticatedRecensementRoute
  '/recensements': typeof AuthenticatedRecensementsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supervisor': typeof AuthenticatedSupervisorRoute
  '/document/$id': typeof AuthenticatedDocumentIdRoute
  '/record/$type': typeof AuthenticatedRecordTypeRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/new': typeof AuthenticatedNewRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recensement': typeof AuthenticatedRecensementRoute
  '/recensements': typeof AuthenticatedRecensementsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supervisor': typeof AuthenticatedSupervisorRoute
  '/': typeof AuthenticatedIndexRoute
  '/document/$id': typeof AuthenticatedDocumentIdRoute
  '/record/$type': typeof AuthenticatedRecordTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recensement': typeof AuthenticatedRecensementRoute
  '/_authenticated/recensements': typeof AuthenticatedRecensementsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/supervisor': typeof AuthenticatedSupervisorRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/document/$id': typeof AuthenticatedDocumentIdRoute
  '/_authenticated/record/$type': typeof AuthenticatedRecordTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accept-invite'
    | '/login'
    | '/register'
    | '/admin'
    | '/new'
    | '/profile'
    | '/recensement'
    | '/recensements'
    | '/settings'
    | '/supervisor'
    | '/document/$id'
    | '/record/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/accept-invite'
    | '/login'
    | '/register'
    | '/admin'
    | '/new'
    | '/profile'
    | '/recensement'
    | '/recensements'
    | '/settings'
    | '/supervisor'
    | '/'
    | '/document/$id'
    | '/record/$type'
  id:
    | '__root__'
    | '/_authenticated'
    | '/about'
    | '/accept-invite'
    | '/login'
    | '/register'
    | '/_authenticated/admin'
    | '/_authenticated/new'
    | '/_authenticated/profile'
    | '/_authenticated/recensement'
    | '/_authenticated/recensements'
    | '/_authenticated/settings'
    | '/_authenticated/supervisor'
    | '/_authenticated/'
    | '/_authenticated/document/$id'
    | '/_authenticated/record/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supervisor': {
      id: '/_authenticated/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof AuthenticatedSupervisorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recensements': {
      id: '/_authenticated/recensements'
      path: '/recensements'
      fullPath: '/recensements'
      preLoaderRoute: typeof AuthenticatedRecensementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recensement': {
      id: '/_authenticated/recensement'
      path: '/recensement'
      fullPath: '/recensement'
      preLoaderRoute: typeof AuthenticatedRecensementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/record/$type': {
      id: '/_authenticated/record/$type'
      path: '/record/$type'
      fullPath: '/record/$type'
      preLoaderRoute: typeof AuthenticatedRecordTypeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/document/$id': {
      id: '/_authenticated/document/$id'
      path: '/document/$id'
      fullPath: '/document/$id'
      preLoaderRoute: typeof AuthenticatedDocumentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecensementRoute: typeof AuthenticatedRecensementRoute
  AuthenticatedRecensementsRoute: typeof AuthenticatedRecensementsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupervisorRoute: typeof AuthenticatedSupervisorRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDocumentIdRoute: typeof AuthenticatedDocumentIdRoute
  AuthenticatedRecordTypeRoute: typeof AuthenticatedRecordTypeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecensementRoute: AuthenticatedRecensementRoute,
  AuthenticatedRecensementsRoute: AuthenticatedRecensementsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupervisorRoute: AuthenticatedSupervisorRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDocumentIdRoute: AuthenticatedDocumentIdRoute,
  AuthenticatedRecordTypeRoute: AuthenticatedRecordTypeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
